package com.moneybook.model;

public class TransactionCategory {
    public static final String TRANSACTION_TYPES_REGEX =
            "TRANSPORT|SHOPPING|HEALTH|FOOD|EDUCATION|ENTERTAINMENT|LOAN|BILLS|INVESTMENT|BORROW|SALARY|GIFT|RENT|INSURANCE|TAX|SAVINGS|DONATION|INTEREST|BONUS|OTHERS";
}
