package com.moneybook.service.group;

import com.moneybook.dto.group.GroupCreateDto;
import com.moneybook.dto.group.GroupDto;
import com.moneybook.exception.ResourceNotFoundException;
import com.moneybook.mappers.GroupMapper;
import com.moneybook.model.FriendGroup;
import com.moneybook.model.GroupMember;
import com.moneybook.model.NormalUser;
import com.moneybook.repository.GroupMembershipRepo;
import com.moneybook.repository.GroupRepo;
import com.moneybook.repository.NormalUserRepo;
import com.soundicly.jnanoidenhanced.jnanoid.NanoIdUtils;
import jakarta.transaction.Transactional;
import lombok.AllArgsConstructor;
import org.springframework.stereotype.Service;

@Service
@AllArgsConstructor
public class GroupService {

    private GroupRepo repo;
    private NormalUserRepo normalUserRepo;
    private GroupMembershipRepo groupMembershipRepo;

    @Transactional
    public GroupDto saveGroup(GroupCreateDto groupCreateDto) throws ResourceNotFoundException {

        // find if the user exists
        NormalUser user = normalUserRepo.findById(groupCreateDto.getUserId()).orElseThrow(() -> new ResourceNotFoundException("User not found"));

        FriendGroup group = GroupMapper.MAPPER.toGroup(groupCreateDto);
        do {
            group.setGroupId(NanoIdUtils.randomNanoId()); // set group_id generated by nanoId
        } while (repo.existsById(group.getGroupId()));
        group.setOwnerName(user.getFirstName() + " " + user.getLastName()); // Set the created_by field to the username of the user
        group.setCreatedBy(user); // Set the owner of the group to the user

        user.getGroups().add(group); // Add the group to the user's list of created groups

        normalUserRepo.save(user);
        FriendGroup groupCreated = repo.saveAndFlush(group);
//      add as a member to the group
        GroupMember membership = GroupMember.builder()
                .groupId(groupCreated.getGroupId())
                .userId(groupCreateDto.getUserId())
                .build();

        System.out.println("Group created: " + groupMembershipRepo.save(membership));
        return GroupMapper.MAPPER.fromGroup(groupCreated);
    }

}
